stages:
  - stage: ALB_Controller
    dependsOn: Infra # يضمن التنفيذ بعد نجاح إنشاء EKS في المرحلة الأولى
    displayName: Install Load Balancer Controller
    jobs:
      - job: Helm_ALB
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          # تثبيت الأدوات اللازمة للتحكم بالعنقود
          - task: KubectlInstaller@0
            inputs:
              versionSpec: 'latest'

          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'

          # ربط الـ Pipeline بالعنقود المخصص (nonprod-eks-cluster)
          - task: AWSShellScript@1
            displayName: "Configure kubeconfig"
            inputs:
              awsCredentials: $(AWS_SERVICE_CONNECTION)
              regionName: $(AWS_REGION)
              scriptType: inline
              inlineScript: |
                aws eks update-kubeconfig --name $(CLUSTER_NAME) --region $(AWS_REGION)

          # إعداد الهوية (IRSA) لتمكين الـ Controller من إنشاء الـ NLB
          - task: AWSShellScript@1
            displayName: "Create Service Account (IRSA)"
            inputs:
              awsCredentials: $(AWS_SERVICE_CO
