stages:
  - stage: ALB_Controller
    displayName: Install Load Balancer Controller
    jobs:
      - job: Helm_ALB
        displayName: Install ALB Controller
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          # تثبيت أدوات kubectl و Helm
          - task: KubectlInstaller@0
            inputs:
              versionSpec: 'latest'

          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'

          # ربط الـ Pipeline بالـ EKS cluster
          - task: AWSShellScript@1
            displayName: "Configure kubeconfig"
            inputs:
              awsCredentials: manar           
              regionName: $(AWS_REGION)        # ✅ تم التصحيح لأحرف كبيرة
              scriptType: inline
              inlineScript: |
                # ✅ استخدام $(...) لضمان جلب القيم من الـ Pipeline
                echo "Configuring kubeconfig for cluster $(CLUSTER_NAME) in region $(AWS_REGION)"
                aws eks update-kubeconfig --name $(CLUSTER_NAME) --region $(AWS_REGION)


          # إنشاء الـ Service Account مع IRSA
          - task: AWSShellScript@1
            displayName: "Create Service Account (IRSA)"
            inputs:
              awsCredentials: manar
              regionName: $(AWS_REGION)
              scriptType: inline
              inlineScript: |
                set -euo pipefail
                echo "Creating namespace $HELM_NAMESPACE"
                kubectl create namespace $HELM_NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
                echo "Creating service account $SERVICE_ACCOUNT"
                kubectl create serviceaccount $SERVICE_ACCOUNT -n $HELM_NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
                
                ROLE_ARN=$(aws iam get-role --role-name $CLUSTER_NAME-nlb-controller-role --query Role.Arn --output text)
                
                echo "Annotating service account with role $ROLE_ARN"
                kubectl annotate serviceaccount $SERVICE_ACCOUNT \
                  eks.amazonaws.com/role-arn=$ROLE_ARN \
                  -n $HELM_NAMESPACE --overwrite

          # تثبيت الـ ALB Controller باستخدام Helm
          - task: AWSShellScript@1
            displayName: "Install Load Balancer Controller"
            inputs:
              awsCredentials: manar
              regionName: $(AWS_REGION)
              scriptType: inline
              inlineScript: |
                helm repo add eks https://aws.github.io/eks-charts
                helm repo update
                helm upgrade --install $HELM_RELEASE eks/aws-load-balancer-controller \
                  -n $HELM_NAMESPACE \
                  --set clusterName=$CLUSTER_NAME \
                  --set serviceAccount.create=false \
                  --set serviceAccount.name=$SERVICE_ACCOUNT
