trigger:
  branches:
    include:
      - main

variables:
  TF_VERSION: "1.5.7"
  ENVIRONMENT: "nonprod"

pool:
  vmImage: ubuntu-latest

stages:
- stage: Infra
  displayName: "Terraform Infra (CLI)"
  jobs:
  - job: Terraform
    displayName: "Terraform Init / Plan / Apply"
    steps:

    - checkout: self

    # Install Terraform
    - bash: |
        curl -fsSL https://releases.hashicorp.com/terraform/$(TF_VERSION)/terraform_$(TF_VERSION)_linux_amd64.zip -o terraform.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
        terraform -version
      displayName: "Install Terraform CLI"

    # Configure AWS Credentials (Service Connection: manar)
    - task: AWSCLI@1
      displayName: "Configure AWS Credentials"
      inputs:
        awsCredentials: manar
        regionName: us-east-1
        command: version

    # Terraform Init
    - bash: |
        cd terraform
        terraform init
      displayName: "Terraform Init"

    # Terraform Plan
    - bash: |
        cd terraform
        terraform plan -var-file=$(ENVIRONMENT).tfvars
      displayName: "Terraform Plan"

    # Terraform Apply
    - bash: |
        cd terraform
        terraform apply -auto-approve -var-file=$(ENVIRONMENT).tfvars
      displayName: "Terraform Apply"
