trigger:
  branches:
    include:
      - main

variables:
  TF_VERSION: "1.5.7"
  ENVIRONMENT: "nonprod"

pool:
  vmImage: ubuntu-latest

stages:
- stage: Infra
  displayName: "Terraform Infra Validation"
  jobs:
  - job: Terraform
    displayName: "Terraform Init / Plan / Apply"
    steps:

    - checkout: self

    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: $(TF_VERSION)

    - task: TerraformTaskV4@4
      displayName: "Terraform Init"
      inputs:
        provider: aws
        command: init
        workingDirectory: terraform
        backendServiceAWS: manar
        backendAWSBucketName: tfs3finalproject
        backendAWSKey: dev/terraform.tfstate
        backendAWSRegion: us-east-1

    - task: TerraformTaskV4@4
      displayName: "Terraform Plan"
      inputs:
        provider: aws
        command: plan
        workingDirectory: terraform
        environmentServiceNameAWS: manar
        commandOptions: "-var-file=$(ENVIRONMENT).tfvars"

    - task: TerraformTaskV4@4
      displayName: "Terraform Apply"
      inputs:
        provider: aws
        command: apply
        workingDirectory: terraform
        environmentServiceNameAWS: manar
        commandOptions: "-auto-approve -var-file=$(ENVIRONMENT).tfvars"
