trigger: none
pr: none

parameters:
  - name: env
    displayName: Environment
    type: string
    default: nonprod
    values: [nonprod, prod]

  - name: destroy
    displayName: Destroy Infra
    type: boolean
    default: false

variables:
  AWS_REGION: us-east-1
  INFRA_CONNECTION: manar
  TF_DIR: terraform
  TF_VAR_FILE: '${{ parameters.env }}.tfvars'

stages:
- stage: Infra
  displayName: "Infrastructure Deployment"
  jobs:
  - job: TerraformInfra
    displayName: "Terraform Infra Only"
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    # Export AWS creds from service connection
    - bash: |
        set -e

        echo "=== 1️⃣ Configure AWS Credentials ==="
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
        echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
        echo "region = $AWS_REGION" >> ~/.aws/config

        echo "=== 2️⃣ Install Terraform CLI ==="
        TF_VERSION=1.5.7
        curl -fsSL https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -o terraform.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
        terraform -version

        echo "=== 3️⃣ Terraform Init & Apply / Destroy ==="
        cd $(TF_DIR)
        terraform init -input=false

        if [ "${{ parameters.destroy }}" = "true" ]; then
          terraform destroy -auto-approve -var-file=$(TF_VAR_FILE)
          echo "✅ Infrastructure destroyed successfully."
        else
          terraform apply -auto-approve -var-file=$(TF_VAR_FILE)
          echo "✅ Infrastructure applied successfully."
        fi

      displayName: "Terraform Infra Only"
      env:
        AWS_ACCESS_KEY_ID: $(INFRA_CONNECTION_AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(INFRA_CONNECTION_AWS_SECRET_ACCESS_KEY)
        AWS_SESSION_TOKEN: $(INFRA_CONNECTION_AWS_SESSION_TOKEN) # إذا كنت تستخدم temporary credentials
        AWS_REGION: $(AWS_REGION)
