trigger: none
pr: none

parameters:
  - name: env
    displayName: Environment
    type: string
    default: nonprod
    values: [nonprod, prod]
  - name: destroy
    displayName: Destroy Infra
    type: boolean
    default: false

variables:
  AWS_REGION: us-east-1
  INFRA_CONNECTION: manar
  TF_DIR: terraform
  TF_VAR_FILE: '${{ parameters.env }}.tfvars'
  CLUSTER_NAME: '${{ parameters.env }}-eks-cluster'
  HELM_NAMESPACE: kube-system
  SERVICE_ACCOUNT: aws-load-balancer-controller
  KUBECONFIG_PATH: $(Pipeline.Workspace)/kubeconfig.yaml

stages:

#################################
# 1️⃣ Stage: Infrastructure (Terraform)
#################################
- stage: Infra
  displayName: "Infrastructure Deployment"
  jobs:
  - job: TerraformJob
    pool: { vmImage: ubuntu-latest }
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs: { terraformVersion: latest }

    - task: AWSShellScript@1
      displayName: "Run Terraform Init & Apply"
      inputs:
        awsCredentials: $(INFRA_CONNECTION)
        regionName: $(AWS_REGION)
        scriptType: inline
        inlineScript: |
          cd $(TF_DIR)
          terraform init -input=false
          if [ "${{ parameters.destroy }}" = "true" ]; then
            terraform destroy -auto-approve -var-file=$(TF_VAR_FILE)
          else
            terraform apply -auto-approve -var-file=$(TF_VAR_FILE)
          fi

