trigger: none
pr: none

parameters:
  - name: env
    displayName: Environment
    type: string
    default: prod
    values: [nonprod, prod]

  - name: destroy
    displayName: Destroy
    type: boolean
    default: false

variables:
  TF_DIR: terraform
  TF_VAR_FILE: '${{ parameters.env }}.tfvars'
  AWS_SERVICE_CONNECTION: manar    # Must exist in Azure DevOps
  AWS_REGION: us-east-1

stages:
  - stage: Infra
    displayName: Infra (Terraform)
    jobs:
      - job: Terraform
        displayName: Terraform
        pool:
          vmImage: ubuntu-latest  # Microsoft-hosted agent
        steps:
          - checkout: self

          # -------------------------
          # Terraform Init
          # -------------------------
          - task: AWSShellScript@1
            displayName: Terraform init
            inputs:
              awsCredentials: $(AWS_SERVICE_CONNECTION)
              regionName: $(AWS_REGION)
              scriptType: inline
              inlineScript: |
                set -euo pipefail
                cd "$(TF_DIR)"
                terraform init -input=false

          # -------------------------
          # Terraform Plan
          # -------------------------
          - task: AWSShellScript@1
            displayName: Terraform plan
            condition: eq('${{ parameters.destroy }}', false)
            inputs:
              awsCredentials: $(AWS_SERVICE_CONNECTION)
              regionName: $(AWS_REGION)
              scriptType: inline
              inlineScript: |
                set -euo pipefail
                cd "$(TF_DIR)"
                if [[ ! -f "$(TF_VAR_FILE)" ]]; then
                  echo "❌ Variables file '$(TF_VAR_FILE)' not found"
                  exit 1
                fi
                terraform plan -out=tfplan -input=false -var-file="$(TF_VAR_FILE)"

          # -------------------------
          # Terraform Plan Destroy
          # -------------------------
          - task: AWSShellScript@1
            displayName: Terraform plan -destroy
            condition: eq('${{ parameters.destroy }}', true)
            inputs:
              awsCredentials: $(AWS_SERVICE_CONNECTION)
              regionName: $(AWS_REGION)
              scriptType: inline
              inlineScript: |
                set -euo pipefail
                cd "$(TF_DIR)"
                if [[ ! -f "$(TF_VAR_FILE)" ]]; then
                  echo "❌ Variables file '$(TF_VAR_FILE)' not found"
                  exit 1
                fi
                terraform plan -destroy -out=tfplan -input=false -var-file="$(TF_VAR_FILE)"

          # -------------------------
          # Terraform Apply
          # -------------------------
          - task: AWSShellScript@1
            displayName: Terraform apply
            inputs:
              awsCredentials: $(AWS_SERVICE_CONNECTION)
              regionName: $(AWS_REGION)
              scriptType: inline
              inlineScript: |
                set -euo pipefail
                cd "$(TF_DIR)"
                if [[ ! -f "tfplan" ]]; then
                  echo "❌ Terraform plan 'tfplan' not found"
                  exit 1
                fi
                terraform apply -auto-approve -input=false tfplan
