trigger: none
pr: none

parameters:
- name: env
  displayName: Environment
  type: string
  default: nonprod
  values: [nonprod, prod]
- name: destroy
  displayName: Destroy
  type: boolean
  default: false

variables:
  TF_DIR: terraform           # ✅ Only use the terraform folder
  TF_VAR_FILE: '${{ parameters.env }}.tfvars'
  AWS_SERVICE_CONNECTION: manar
  AWS_REGION: us-east-1

stages:
# =========================
# 1️⃣ Terraform Stage Only
# =========================
- stage: Infra
  displayName: Terraform Infra
  jobs:
    - job: Terraform
      pool:
        vmImage: ubuntu-latest
      steps:
        - checkout: self

        # Debug: check terraform folder contents
        - script: |
            echo "Terraform folder contents ($(TF_DIR)):"
            ls -la $(TF_DIR)
          displayName: "Debug: List Terraform files"

        # Install Terraform
        - task: TerraformInstaller@1
          displayName: Install Terraform
          inputs:
            terraformVersion: latest

        # Terraform init
        - task: AWSShellScript@1
          displayName: Terraform init
          inputs:
            awsCredentials: $(AWS_SERVICE_CONNECTION)
            regionName: $(AWS_REGION)
            scriptType: inline
            inlineScript: |
              set -euo pipefail
              cd "$(TF_DIR)"
              terraform init -input=false

        # Terraform plan (create/update)
        - task: AWSShellScript@1
          displayName: Terraform plan (robust)
          condition: eq('${{ parameters.destroy }}', false)
          inputs:
            awsCredentials: $(AWS_SERVICE_CONNECTION)
            regionName: $(AWS_REGION)
            scriptType: inline
            inlineScript: |
              set -euo pipefail
              cd "$(TF_DIR)"
              if [[ ! -f "$(TF_VAR_FILE)" ]]; then
                echo "❌ Error: Variables file '$(TF_VAR_FILE)' does not exist in $(TF_DIR)"
                exit 1
              fi
              terraform plan -out=tfplan -input=false -var-file="$(TF_VAR_FILE)"

        # Terraform plan (destroy)
        - task: AWSShellScript@1
          displayName: Terraform plan -destroy (robust)
          condition: eq('${{ parameters.destroy }}', true)
          inputs:
            awsCredentials: $(AWS_SERVICE_CONNECTION)
            regionName: $(AWS_REGION)
            scriptType: inline
            inlineScript: |
              set -euo pipefail
              cd "$(TF_DIR)"
              if [[ ! -f "$(TF_VAR_FILE)" ]]; then
                echo "❌ Error: Variables file '$(TF_VAR_FILE)' does not exist in $(TF_DIR)"
                exit 1
              fi
              terraform plan -destroy -out=tfplan -input=false -var-file="$(TF_VAR_FILE)"

        # Terraform apply
        - task: AWSShellScript@1
          displayName: Terraform apply (robust)
          inputs:
            awsCredentials: $(AWS_SERVICE_CONNECTION)
            regionName: $(AWS_REGION)
            scriptType: inline
            inlineScript: |
              set -euo pipefail
              cd "$(TF_DIR)"
              if [[ ! -f "tfplan" ]]; then
                echo "❌ Error: Terraform plan 'tfplan' does not exist. Did the plan stage fail?"
                exit 1
              fi
              terraform apply -auto-approve -input=false tfplan
