trigger: none
pr: none

parameters:
  - name: env
    type: string
    default: nonprod
    values: [nonprod, prod]

  - name: destroy
    type: boolean
    default: false

variables:
  TF_DIR: terraform
  TF_VAR_FILE: '${{ parameters.env }}.tfvars'
  AWS_REGION: us-east-1
  AWS_SERVICE_CONNECTION: manar 

stages:
- stage: Infra
  displayName: Terraform Infra
  jobs:
  - job: Terraform
    pool:
      name: aws-self-hosted
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: latest

    - task: AWSShellScript@1
      displayName: Terraform Init
      inputs:
        awsCredentials: $(AWS_SERVICE_CONNECTION)
        regionName: $(AWS_REGION)
        scriptType: inline
        inlineScript: |
          set -e
          cd $(TF_DIR)
          terraform init

    - task: AWSShellScript@1
      displayName: Terraform Plan
      condition: eq('${{ parameters.destroy }}', false)
      inputs:
        awsCredentials: $(AWS_SERVICE_CONNECTION)
        regionName: $(AWS_REGION)
        scriptType: inline
        inlineScript: |
          set -e
          cd $(TF_DIR)
          terraform plan -out=tfplan -var-file=$(TF_VAR_FILE)

    - task: AWSShellScript@1
      displayName: Terraform Destroy Plan
      condition: eq('${{ parameters.destroy }}', true)
      inputs:
        awsCredentials: $(AWS_SERVICE_CONNECTION)
        regionName: $(AWS_REGION)
        scriptType: inline
        inlineScript: |
          set -e
          cd $(TF_DIR)
          terraform plan -destroy -out=tfplan -var-file=$(TF_VAR_FILE)

    - task: AWSShellScript@1
      displayName: Terraform Apply
      inputs:
        awsCredentials: $(AWS_SERVICE_CONNECTION)
        regionName: $(AWS_REGION)
        scriptType: inline
        inlineScript: |
          set -e
          cd $(TF_DIR)
          terraform apply -auto-approve tfplan
