trigger: none
pr: none

parameters:
  - name: env
    displayName: Environment
    type: string
    default: nonprod
    values: [nonprod, prod]

  - name: destroy
    displayName: Destroy Infra
    type: boolean
    default: false

variables:
  AWS_REGION: us-east-1
  INFRA_CONNECTION: manar
  TF_DIR: terraform
  TF_VAR_FILE: '${{ parameters.env }}.tfvars'

stages:
- stage: Infra
  displayName: "Infrastructure Deployment"
  jobs:
  - job: TerraformJob
    displayName: "Terraform Infra"
    pool:
      vmImage: ubuntu-latest  # لو Self-hosted Agent، ضع اسم الـ agent هنا
    steps:

    - checkout: self

    # Terraform Init / Apply / Destroy
    - task: AWSShellScript@1
      displayName: "Terraform Init & Apply"
      inputs:
        awsCredentials: $(INFRA_CONNECTION)
        regionName: $(AWS_REGION)
        scriptType: inline
        inlineScript: |
          set -e
          cd $(TF_DIR)
          terraform init -input=false

          if [ "${{ parameters.destroy }}" = "true" ]; then
            terraform destroy -auto-approve -var-file=$(TF_VAR_FILE)
          else
            terraform apply -auto-approve -var-file=$(TF_VAR_FILE)
