trigger: none
pr: none

parameters:
  - name: env
    displayName: Environment
    type: string
    default: nonprod
    values: [nonprod, prod]
  - name: destroy
    displayName: Destroy Infrastructure
    type: boolean
    default: false

variables:
  TF_DIR: terraform
  TF_VAR_FILE: '${{ parameters.env }}.tfvars'
  AWS_SERVICE_CONNECTION: manar
  AWS_REGION: us-east-1

stages:
  - stage: Infra
    displayName: "Infra (Terraform)"
    jobs:
      - job: Terraform
        displayName: "Terraform Execution"
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: latest

          # 1️⃣ Init: تحميل المكتبات
          - task: AWSShellScript@1
            displayName: "Terraform Init"
            inputs:
              awsCredentials: $(AWS_SERVICE_CONNECTION)
              regionName: $(AWS_REGION)
              scriptType: inline
              inlineScript: |
                set -euo pipefail
                cd "$(TF_DIR)"
                terraform init -input=false

          # 2️⃣ Plan: هنا بيظهر خطأ "enable_irsa" لو لسه موجود في الكود
          - task: AWSShellScript@1
            displayName: "Terraform Plan"
            inputs:
              awsCredentials: $(AWS_SERVICE_CONNECTION)
              regionName: $(AWS_REGION)
              scriptType: inline
              inlineScript: |
                set -euo pipefail
                cd "$(TF_DIR)"
                # لو parameters.destroy بـ true هيعمل plan للمسح، ولو false هيعمل plan للإنشاء
                ACTION_FLAG=""
                if [ "${{ parameters.destroy }}" = "true" ]; then ACTION_FLAG="-destroy"; fi
                
                terraform plan $ACTION_FLAG -out=tfplan -input=false -var-file="$(TF_VAR_FILE)"

          # 3️⃣ Apply: تنفيذ ما تم تخطيطه
          - task: AWSShellScript@1
            displayName: "Terraform Apply"
            inputs:
              awsCredentials: $(AWS_SERVICE_CONNECTION)
              regionName: $(AWS_REGION)
              scriptType: inline
              inlineScript: |
                set -euo pipefail
                cd "$(TF_DIR)"
                # التنفيذ بيعتمد فقط على ملف الـ tfplan الناتج من الخطوة اللي فاتت
                terraform apply -auto-approve -input=false tfplan