trigger: none
pr: none

parameters:
  - name: env
    displayName: Environment
    type: string
    default: prod
    values: [nonprod, prod]

  - name: destroy
    displayName: Destroy
    type: boolean
    default: false

variables:
  TF_DIR: terraform
  TF_VAR_FILE: '${{ parameters.env }}.tfvars'
  AWS_SERVICE_CONNECTION: manar
  AWS_REGION: us-east-1

stages:
  - stage: Infra
    displayName: Infra (Terraform)
    jobs:
      - job: Terraform
        displayName: Terraform
        pool:
          name: aws-self-hosted
        steps:
          - checkout: self

          - task: AWSShellScript@1
            displayName: Terraform init
            inputs:
              awsCredentials: $(AWS_SERVICE_CONNECTION)
              regionName: $(AWS_REGION)
              scriptType: inline
              inlineScript: |
                set -euo pipefail
                cd "$(TF_DIR)"
                terraform init -input=false

          - task: AWSShellScript@1
            displayName: Terraform plan
            condition: eq('${{ parameters.destroy }}', false)
            inputs:
              awsCredentials: $(AWS_SERVICE_CONNECTION)
              regionName: $(AWS_REGION)
              scriptType: inline
              inlineScript: |
                set -euo pipefail
                cd "$(TF_DIR)"
                terraform plan -out=tfplan -input=false -var-file="$(TF_VAR_FILE)"

          - task: AWSShellScript@1
            displayName: Terraform plan -destroy
            condition: eq('${{ parameters.destroy }}', true)
            inputs:
              awsCredentials: $(AWS_SERVICE_CONNECTION)
              regionName: $(AWS_REGION)
              scriptType: inline
              inlineScript: |
                set -euo pipefail
                cd "$(TF_DIR)"
                terraform plan -destroy -out=tfplan -input=false -var-file="$(TF_VAR_FILE)"

          - task: AWSShellScript@1
            displayName: Terraform apply
            inputs:
              awsCredentials: $(AWS_SERVICE_CONNECTION)
              regionName: $(AWS_REGION)
              scriptType: inline
              inlineScript: |
                set -euo pipefail
                cd "$(TF_DIR)"
                terraform apply -auto-approve -input=false tfplan