trigger: none
pr: none

parameters:
  - name: env
    displayName: Environment
    type: string
    default: nonprod
    values: [nonprod, prod]
  - name: destroy
    displayName: Destroy Infrastructure
    type: boolean
    default: false

variables:
  TF_DIR: terraform
  TF_VAR_FILE: '${{ parameters.env }}.tfvars'
  AWS_SERVICE_CONNECTION: manar
  AWS_REGION: us-east-1

stages:
  - stage: Infra
    displayName: "Infra (Terraform)"
    jobs:
      - job: Terraform
        displayName: "Terraform Execution"
        pool:
          vmImage: ubuntu-latest # أو aws-self-hosted حسب إعدادات الـ Agent عندك
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: latest

          # 1️⃣ Terraform Init
          - task: AWSShellScript@1
            displayName: "Terraform Init"
            inputs:
              awsCredentials: $(AWS_SERVICE_CONNECTION)
              regionName: $(AWS_REGION)
              scriptType: inline
              inlineScript: |
                set -euo pipefail
                cd "$(TF_DIR)"
                terraform init -input=false

          # 2️⃣ Terraform Plan (Normal)
          - task: AWSShellScript@1
            displayName: "Terraform Plan"
            condition: eq('${{ parameters.destroy }}', false)
            inputs:
              awsCredentials: $(AWS_SERVICE_CONNECTION)
              regionName: $(AWS_REGION)
              scriptType: inline
              inlineScript: |
                set -euo pipefail
                cd "$(TF_DIR)"
                terraform plan -out=tfplan -input=false -var-file="$(TF_VAR_FILE)"

          # 3️⃣ Terraform Plan (Destroy)
          - task: AWSShellScript@1
            displayName: "Terraform Plan - Destroy"
            condition: eq('${{ parameters.destroy }}', true)
            inputs:
              awsCredentials: $(AWS_SERVICE_CONNECTION)
              regionName: $(AWS_REGION)
              scriptType: inline
              inlineScript: |
                set -euo pipefail
                cd "$(TF_DIR)"
                terraform plan -destroy -out=tfplan -input=false -var-file="$(TF_VAR_FILE)"

          # 4️⃣ Terraform Apply
          - task: AWSShellScript@1
            displayName: "Terraform Apply"
            inputs:
              awsCredentials: $(AWS_SERVICE_CONNECTION)
              regionName: $(AWS_REGION)
              scriptType: inline
              inlineScript: |
                set -euo pipefail
                cd "$(TF_DIR)"
                # سيقوم بتطبيق الخطة سواء كانت Apply أو Destroy بناءً على ملف tfplan
                terraform apply -auto-approve -input=false tfplan