environment         = "prod"
aws_region          = "us-east-1"
vpc_name            = "final-project-vpc"
azs                 = ["us-east-1a", "us-east-1b"]
eks_cluster_name    = "prod-eks-cluster"
cluster_name        = "prod-eks-cluster"
node_instance_types = ["t3.small"]
desired_capacity    = 3
min_size            = 1
max_size            = 4
target_group_port   = 80
# nlb_name          = null
# nlb_arn           = null
