apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: appmanar-db-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: myapp-db
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/myapp-db
        property: username
    - secretKey: password
      remoteRef:
        key: secret/myapp-db
        property: password
