apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mongodb-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MONGODB_URI: "{{ .uri }}"
        MONGODB_USERNAME: "{{ .username }}"
        MONGODB_PASSWORD: "{{ .password }}"
        MONGODB_DATABASE: "{{ .database }}"
  data:
    - secretKey: uri
      remoteRef:
        key: myapp/mongodb
        property: uri
    - secretKey: username
      remoteRef:
        key: myapp/mongodb
        property: username
    - secretKey: password
      remoteRef:
        key: myapp/mongodb
        property: password
    - secretKey: database
      remoteRef:
        key: myapp/mongodb
        property: database
