apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-mongodb-conf
  namespace: datadog
data:
  mongodb.yaml: |
    init_config:

    instances:
      - hosts:
          - <MONGODB_SRV_ADDRESS>
        username: datadog
        password: ENC[datadog_user_password]
        database: admin
        options:
          authSource: admin
        tags:
          - env:nonprod
          - service:manar-app
        
        # Collect metrics
        collect_metrics: true
        
        # Collect slow operations
        operations:
          enabled: true
          
        # Collect replica set metrics
        replica_check: true
        
        # SSL/TLS
        tls: true
        tls_allow_invalid_certificates: false
